### ISSUE TITLE
Error: spawn kpm ENOENT

### ISSUE THREAD

**Issue by jwoertink** [jchannon/generator-nancy#2]
Not sure if this package is still good or not, but after running `yo nancy` following [this tutorial](http://blog.jonathanchannon.com/2014/08/05/nancy-aspnetvnext-osx-sublime-text/)

``` text
? What's the name of your Nancy ASP.NET application? nancy-demo
identical NuGet.config
   create nancy-demo/HomeModule.cs
   create nancy-demo/Startup.cs
   create nancy-demo/project.json
/Users/jeremywoertink/.cache/yeoman
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn kpm ENOENT
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any idea?

**Comment by jchannon** [comment]
This is severely out of date. Try the aspnet generator instead

**Comment by jwoertink** [comment]
ok thanks.
